CREATE TABLE billionaires (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  company VARCHAR(250) DEFAULT NULL,
  wealth VARCHAR(250) DEFAULT NULL
);